### ISSUE TITLE
Any plans to publish your code?

### ISSUE THREAD

**Issue by kiitaamuuraa** [Lucas2012/EvolvingGraphicalPlanner#1]
I read your EGP paper, and I appreciate your great work. However, I am still struggling to reach a complete understanding of your work. If you publish your code, it would be helpful to my research. 
Thank you.

**Comment by Lucas2012** [comment]
Hi,
Thanks for the interest. Yes, the code will be released soon (the plan got distracted by other things). Feel free to directly email me with your questions on the details of the paper.
